### ISSUE TITLE
WordPress 5.0 Support

### ISSUE THREAD

**Issue by MillerMedia** [Miller-Media/protect-the-children#2]
Needed!

**Comment by MillerMedia** [comment]
Specifically, the Gutenberg editor is Javascript based and the current plugin only supports pre-5.0 WordPress versions that generate the 'protect the children' option using a PHP WordPress hook on the meta box where the password protection is set.

**Comment by mohsinrasool** [comment]
@MillerMedia I want to work on this. Can you please assign this issue to me? 

Thanks

**Comment by MillerMedia** [comment]
This is great, thanks @mohsinrasool . I've been looking forward to having somebody work on this for a while, let me know if you have any questions. As you work on it, keep in mind that we will want to maintain support for < 5.0 support as well.

**Comment by MillerMedia** [comment]
This has been completed in pull request #3
