### ISSUE TITLE
Screenshots need updating

### ISSUE THREAD

**Issue by MillerMedia** [Miller-Media/protect-the-children#5]
With the update to Gutenberg we need to show screenshots of how it appears in Gutenberg on the WordPress.org plugin page. We should keep the old screenshots and add caption specifying pre-Gutenberg and post-Gutenberg views.

**Comment by deltafactory** [comment]
What's the easiest way to submit a PR for this, since the GH repo doesn't mimic the WP SVN repo file structure?

**Comment by MillerMedia** [comment]
Hi @deltafactory , this is a good point as we have been using this repository to track code changes rather than changes to the WP repo assets. I'd like to keep the repository clean for functionality/code changes so let's use this ticket thread if you want to post them here. After that we can update the repository on our end. Also, please let us know your WordPress.com username (if it is different than @deltafactory ) so we can add it as a contributor to the plugin after you submit. Thanks!

**Comment by deltafactory** [comment]
Here's what I came up with - matching the set from the classic editor. There's a small gradient which I can leave out if you don't like it.

Screenshot 5:
![screenshot-5](https://user-images.githubusercontent.com/547778/66787582-3e666c80-eeb2-11e9-8e98-3aa0b15de337.png)

Screenshot 6:
![screenshot-6](https://user-images.githubusercontent.com/547778/66787583-3e666c80-eeb2-11e9-817f-d13209597d59.png)

Screenshot 7:
![screenshot-7](https://user-images.githubusercontent.com/547778/66787585-3e666c80-eeb2-11e9-839d-646735640c4a.png)

I'm @deltafactory on WP.com as well.

**Comment by MillerMedia** [comment]
Great, thank you! We will get these updated shortly and add you as a contributor. Appreciate the help on this!

**Comment by mm-stuart** [comment]
Resolved with version 1.3.4. Thank you @deltafactory !
